{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "c051a56c",
   "metadata": {},
   "source": [
    "# Philippines' Freedom of Information website scraper and analysis\n",
    "\n",
    "**(Data from September 2016-January 19 and ongoing)**\n",
    "\n",
    "Below scrapes and processes requests data from the Philippines' Freedom of Information website **(www.foi.gov.ph)** and combining the same with an **existing file** of **older FOI requests from 2016.** \n",
    "\n",
    "The goal is to create a single database of these requests (which we will do in a separate notebook) and analyze them such as:\n",
    "\n",
    "Which agency received the most number of requests?\n",
    "\n",
    "How many requests had been denied/approved?\n",
    "\n",
    "What type of requests are most common?\n",
    "\n",
    "Some background: The FOI website is in compliance with Executive Order No. 2, Series of 2016 by President Rodrigo Duterte that institutionalized freedom of information in the Executive branch of government."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "99cb2d6e",
   "metadata": {},
   "source": [
    "## Do your imports"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "f300e9ca",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/prinzmagtulis/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pandas/compat/__init__.py:124: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.\n",
      "  warnings.warn(msg)\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "\n",
    "import time\n",
    "import requests\n",
    "import re\n",
    "\n",
    "from selenium import webdriver\n",
    "from selenium.webdriver.common.keys import Keys\n",
    "from selenium.webdriver.support.ui import Select\n",
    "from selenium.webdriver.support.ui import WebDriverWait\n",
    "from selenium.webdriver.support import expected_conditions as EC\n",
    "from selenium.webdriver.common.by import By\n",
    "\n",
    "from webdriver_manager.chrome import ChromeDriverManager\n",
    "\n",
    "from bs4 import BeautifulSoup"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1cff23bb",
   "metadata": {},
   "source": [
    "## Open a new browser to be automatically controlled by Selenium"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "9f61c1a4",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "====== WebDriver manager ======\n",
      "Could not get version for google-chrome with the any command: /Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --version\n",
      "Current google-chrome version is UNKNOWN\n",
      "Get LATEST chromedriver version for UNKNOWN google-chrome\n",
      "Driver [/Users/prinzmagtulis/.wdm/drivers/chromedriver/mac64/97.0.4692.71/chromedriver] found in cache\n",
      "/var/folders/01/dz49lpcd4qq_yksvf114xzfc0000gn/T/ipykernel_3385/1503906442.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object\n",
      "  driver = webdriver.Chrome(ChromeDriverManager().install())\n"
     ]
    }
   ],
   "source": [
    "driver = webdriver.Chrome(ChromeDriverManager().install())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "b9e486a2",
   "metadata": {},
   "outputs": [],
   "source": [
    "driver.get(\"https://www.foi.gov.ph/requests\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1952c205",
   "metadata": {},
   "source": [
    "Note: That is the part of the website supposedly containing all FOI requests."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "54141a3c",
   "metadata": {},
   "source": [
    "## Start locating and isolating elements\n",
    "\n",
    "Some methods are:\n",
    "\n",
    "By.TAG\n",
    "\n",
    "By.CLASS_NAME\n",
    "\n",
    "By.ID\n",
    "\n",
    "By.XPATH\n",
    "\n",
    "By.CSS_SELECTOR"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "e0470198",
   "metadata": {},
   "outputs": [],
   "source": [
    "tabs = driver.find_elements(By.CLASS_NAME, \"col-xxs-12 col-xs-12 col-sm-8\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e94445c1",
   "metadata": {},
   "source": [
    "Used **BeautifulSoup** on this part just because I want to clearly see the elements I need to **isolate**."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "3e39c546",
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "my_url = \"https://www.foi.gov.ph/requests\"\n",
    "foi_html = requests.get(my_url).content\n",
    "#print(type(foi_html))\n",
    "#print(foi_html)\n",
    "\n",
    "#foi_list = BeautifulSoup(foi_html, \"html.parser\")\n",
    "#print(type(foi_list))\n",
    "#print(foi_list.prettify())"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "994bc1b4",
   "metadata": {},
   "source": [
    "## Actual scraping"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "60803cff",
   "metadata": {},
   "source": [
    "Now comes the main part: interacting with the pages and setting Selenium to scrape each page. We then put scraped information in a **list of dictionaries** and then into a **single data frame.** \n",
    "\n",
    "Kudos to my friend, Vincent, for some help in using **CSS_SELECTOR** as a locator since I'm not familiar with it."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "478b4c80",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n",
      "Reading a page\n"
     ]
    }
   ],
   "source": [
    "dataset = []\n",
    "while True:\n",
    "    try:\n",
    "        print('Reading a page')\n",
    "        WebDriverWait(driver, 4).until(\n",
    "            EC.presence_of_element_located((By.CSS_SELECTOR, \".col-xxs-12.col-xs-12.col-sm-8\"))\n",
    "        )\n",
    "        tabs = driver.find_elements(By.CSS_SELECTOR, \".col-xxs-12.col-xs-12.col-sm-8\")\n",
    "        for tab in tabs:\n",
    "            try:\n",
    "                all_div = tab.find_elements(By.CSS_SELECTOR, '.component-panel')\n",
    "            except:\n",
    "                break\n",
    "            for div in all_div[1:]:\n",
    "                data={}\n",
    "                data ['agency'] = div.find_element(By.TAG_NAME, 'span').text\n",
    "                data ['date'] = div.find_element(By.TAG_NAME, 'p').get_attribute('title')\n",
    "                data ['title'] = div.find_element(By.TAG_NAME, 'h4').text\n",
    "                data ['status'] = div.find_element(By.TAG_NAME, 'label').text\n",
    "                data ['purpose'] = div.find_elements(By.TAG_NAME, 'span')[2].text\n",
    "                data ['period_covered'] = div.find_elements(By.TAG_NAME, 'span')[3].text\n",
    "                data ['link'] = div.find_element(By.TAG_NAME, 'a').get_attribute('href')\n",
    "                dataset.append(data)\n",
    "    except:\n",
    "        break\n",
    "\n",
    "    try:\n",
    "        driver.find_element(By.XPATH, \"/html/body/section/div/div/div/div[2]/div/div/div/a\").click()\n",
    "    except:\n",
    "        print(\"Nothing more.\")\n",
    "        break"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "cf532a2a",
   "metadata": {},
   "source": [
    "## Generate your (first) data frame\n",
    "\n",
    "This is now all pandas."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "951c2fa0",
   "metadata": {},
   "source": [
    "So, some caveats:\n",
    "\n",
    "First, the **ALL REQUESTS** tab apparently only contains data for about the past 40 or so days (in this case from **December 7, 2021**). Hence, we can only scrape until that level-- that represent only or **about 6%** of what the website says as **\"93,373 requests\"**."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "99836c2f",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>agency</th>\n",
       "      <th>date</th>\n",
       "      <th>title</th>\n",
       "      <th>status</th>\n",
       "      <th>purpose</th>\n",
       "      <th>period_covered</th>\n",
       "      <th>link</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>PSA</td>\n",
       "      <td>January 20, 2022</td>\n",
       "      <td>Copy of PSA Birth certificate (Mary Anne Robis...</td>\n",
       "      <td>PENDING</td>\n",
       "      <td>Clarification for Misrepresentation of COC</td>\n",
       "      <td>01/20/1950 - 01/20/2022</td>\n",
       "      <td>https://www.foi.gov.ph/requests/aglzfmVmb2ktcG...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>DOST-ASTI</td>\n",
       "      <td>January 20, 2022</td>\n",
       "      <td>Daily Rainfall Data surrounding Mt. Banahaw fr...</td>\n",
       "      <td>PENDING</td>\n",
       "      <td>Research and Instruction</td>\n",
       "      <td>01/01/2010 - 12/31/2020</td>\n",
       "      <td>https://www.foi.gov.ph/requests/aglzfmVmb2ktcG...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>DSWD</td>\n",
       "      <td>January 20, 2022</td>\n",
       "      <td>SAP beneficiaries of San Roque Northern Samar</td>\n",
       "      <td>PENDING</td>\n",
       "      <td>Research on Good Governance</td>\n",
       "      <td>04/01/2020 - 12/31/2021</td>\n",
       "      <td>https://www.foi.gov.ph/requests/aglzfmVmb2ktcG...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>DA</td>\n",
       "      <td>January 20, 2022</td>\n",
       "      <td>Goat and Carabao Dispersal San Roque Northern ...</td>\n",
       "      <td>PENDING</td>\n",
       "      <td>Research on Good Governance</td>\n",
       "      <td>01/01/2013 - 12/31/2021</td>\n",
       "      <td>https://www.foi.gov.ph/requests/aglzfmVmb2ktcG...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>SSS</td>\n",
       "      <td>January 20, 2022</td>\n",
       "      <td>SSS sickness and EC benefits positive COVID-19</td>\n",
       "      <td>PENDING</td>\n",
       "      <td>Follow on SSS sickness application</td>\n",
       "      <td>09/24/2021 - 10/10/2021</td>\n",
       "      <td>https://www.foi.gov.ph/requests/aglzfmVmb2ktcG...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6414</th>\n",
       "      <td>DOH</td>\n",
       "      <td>December 07, 2021</td>\n",
       "      <td>VAXCERT</td>\n",
       "      <td>SUCCESSFUL</td>\n",
       "      <td>Follow up request</td>\n",
       "      <td>11/15/2021 - 12/07/2021</td>\n",
       "      <td>https://www.foi.gov.ph/requests/aglzfmVmb2ktcG...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6415</th>\n",
       "      <td>DOH</td>\n",
       "      <td>December 07, 2021</td>\n",
       "      <td>Vax Certificate</td>\n",
       "      <td>SUCCESSFUL</td>\n",
       "      <td>Request for vax certificate</td>\n",
       "      <td>12/01/2021 - 12/07/2021</td>\n",
       "      <td>https://www.foi.gov.ph/requests/aglzfmVmb2ktcG...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6416</th>\n",
       "      <td>OWWA</td>\n",
       "      <td>December 07, 2021</td>\n",
       "      <td>OFW DOLE-AKAP Cash Assistance</td>\n",
       "      <td>SUCCESSFUL</td>\n",
       "      <td>Cash Releasing of DOLE AKAP cash assistance</td>\n",
       "      <td>11/13/2021 - 12/07/2021</td>\n",
       "      <td>https://www.foi.gov.ph/requests/aglzfmVmb2ktcG...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6417</th>\n",
       "      <td>DOH</td>\n",
       "      <td>December 07, 2021</td>\n",
       "      <td>Urgent! Vaccination Certification For Travel</td>\n",
       "      <td>SUCCESSFUL</td>\n",
       "      <td>For Travel on December 9</td>\n",
       "      <td>07/26/2021 - 08/23/2021</td>\n",
       "      <td>https://www.foi.gov.ph/requests/aglzfmVmb2ktcG...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6418</th>\n",
       "      <td>PCAARRD</td>\n",
       "      <td>December 07, 2021</td>\n",
       "      <td>Stream flow Data in the Province of Cavite</td>\n",
       "      <td>DENIED</td>\n",
       "      <td>National Irrigation Administration - National ...</td>\n",
       "      <td>12/06/2015 - 12/06/2021</td>\n",
       "      <td>https://www.foi.gov.ph/requests/aglzfmVmb2ktcG...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>6419 rows × 7 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "         agency               date  \\\n",
       "0           PSA   January 20, 2022   \n",
       "1     DOST-ASTI   January 20, 2022   \n",
       "2          DSWD   January 20, 2022   \n",
       "3            DA   January 20, 2022   \n",
       "4           SSS   January 20, 2022   \n",
       "...         ...                ...   \n",
       "6414        DOH  December 07, 2021   \n",
       "6415        DOH  December 07, 2021   \n",
       "6416       OWWA  December 07, 2021   \n",
       "6417        DOH  December 07, 2021   \n",
       "6418    PCAARRD  December 07, 2021   \n",
       "\n",
       "                                                  title      status  \\\n",
       "0     Copy of PSA Birth certificate (Mary Anne Robis...     PENDING   \n",
       "1     Daily Rainfall Data surrounding Mt. Banahaw fr...     PENDING   \n",
       "2         SAP beneficiaries of San Roque Northern Samar     PENDING   \n",
       "3     Goat and Carabao Dispersal San Roque Northern ...     PENDING   \n",
       "4        SSS sickness and EC benefits positive COVID-19     PENDING   \n",
       "...                                                 ...         ...   \n",
       "6414                                            VAXCERT  SUCCESSFUL   \n",
       "6415                                    Vax Certificate  SUCCESSFUL   \n",
       "6416                      OFW DOLE-AKAP Cash Assistance  SUCCESSFUL   \n",
       "6417       Urgent! Vaccination Certification For Travel  SUCCESSFUL   \n",
       "6418         Stream flow Data in the Province of Cavite      DENIED   \n",
       "\n",
       "                                                purpose  \\\n",
       "0            Clarification for Misrepresentation of COC   \n",
       "1                              Research and Instruction   \n",
       "2                           Research on Good Governance   \n",
       "3                           Research on Good Governance   \n",
       "4                    Follow on SSS sickness application   \n",
       "...                                                 ...   \n",
       "6414                                  Follow up request   \n",
       "6415                        Request for vax certificate   \n",
       "6416        Cash Releasing of DOLE AKAP cash assistance   \n",
       "6417                           For Travel on December 9   \n",
       "6418  National Irrigation Administration - National ...   \n",
       "\n",
       "               period_covered  \\\n",
       "0     01/20/1950 - 01/20/2022   \n",
       "1     01/01/2010 - 12/31/2020   \n",
       "2     04/01/2020 - 12/31/2021   \n",
       "3     01/01/2013 - 12/31/2021   \n",
       "4     09/24/2021 - 10/10/2021   \n",
       "...                       ...   \n",
       "6414  11/15/2021 - 12/07/2021   \n",
       "6415  12/01/2021 - 12/07/2021   \n",
       "6416  11/13/2021 - 12/07/2021   \n",
       "6417  07/26/2021 - 08/23/2021   \n",
       "6418  12/06/2015 - 12/06/2021   \n",
       "\n",
       "                                                   link  \n",
       "0     https://www.foi.gov.ph/requests/aglzfmVmb2ktcG...  \n",
       "1     https://www.foi.gov.ph/requests/aglzfmVmb2ktcG...  \n",
       "2     https://www.foi.gov.ph/requests/aglzfmVmb2ktcG...  \n",
       "3     https://www.foi.gov.ph/requests/aglzfmVmb2ktcG...  \n",
       "4     https://www.foi.gov.ph/requests/aglzfmVmb2ktcG...  \n",
       "...                                                 ...  \n",
       "6414  https://www.foi.gov.ph/requests/aglzfmVmb2ktcG...  \n",
       "6415  https://www.foi.gov.ph/requests/aglzfmVmb2ktcG...  \n",
       "6416  https://www.foi.gov.ph/requests/aglzfmVmb2ktcG...  \n",
       "6417  https://www.foi.gov.ph/requests/aglzfmVmb2ktcG...  \n",
       "6418  https://www.foi.gov.ph/requests/aglzfmVmb2ktcG...  \n",
       "\n",
       "[6419 rows x 7 columns]"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df = pd.DataFrame(dataset)\n",
    "df"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4e4cb99a",
   "metadata": {},
   "source": [
    "### Change date to date time"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "88f174a1",
   "metadata": {},
   "outputs": [],
   "source": [
    "df.date = pd.to_datetime(df.date)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "57c22fa2",
   "metadata": {},
   "source": [
    "## Second (and larger) data frame\n",
    "\n",
    "Because the first df obviously lacked a large number of data, we asked the PCOO, which manages the FOI website, for earlier data which are all available through \"https://docs.google.com/spreadsheets/d/1kblO1_-gL65qXu_EJJBvc59UUHBQ7K3c/edit?fbclid=IwAR1rYDiXlMcllT7Ko4bEJUYGTAIWIloljXhk4EmUhJo0ehHksZ3vYIFDkw0#gid=875187444\".\n",
    "\n",
    "It lists down all requests from **September 2016-December 2021.** We need to clean the data though (i.e. convert dates, remove duplicates) so that we can process it later on."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "ee7f2108",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>DATE CREATED</th>\n",
       "      <th>AGENCY</th>\n",
       "      <th>TITLE OF REQUESTED DOCUMENTS</th>\n",
       "      <th>PERIOD/COVERAGE</th>\n",
       "      <th>PURPOSE</th>\n",
       "      <th>STATUS</th>\n",
       "      <th>EXTENDED?</th>\n",
       "      <th>REASON FOR DENIAL</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2016-11-25 (01:26:40.574) HKT</td>\n",
       "      <td>DOTr</td>\n",
       "      <td>clark green city update</td>\n",
       "      <td>11/25/2016 - 11/25/2016</td>\n",
       "      <td>for update</td>\n",
       "      <td>CLOSED</td>\n",
       "      <td>NO</td>\n",
       "      <td>—</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2016-11-25 (01:35:34.481) HKT</td>\n",
       "      <td>PNP</td>\n",
       "      <td>Crime Statatistics and Programs to Combat it</td>\n",
       "      <td>01/01/2000 - 11/25/2016</td>\n",
       "      <td>School Paper</td>\n",
       "      <td>CLOSED</td>\n",
       "      <td>NO</td>\n",
       "      <td>—</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2016-11-25 (02:22:02.812) HKT</td>\n",
       "      <td>DICT</td>\n",
       "      <td>List of .gov.ph sub-domains</td>\n",
       "      <td>11/25/2015 - 11/25/2016</td>\n",
       "      <td>Research and development</td>\n",
       "      <td>ACCEPTED</td>\n",
       "      <td>NO</td>\n",
       "      <td>—</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2016-11-25 (07:33:31.050) HKT</td>\n",
       "      <td>DOH</td>\n",
       "      <td>HIV stats in the Philippines</td>\n",
       "      <td>11/25/2015 - 11/25/2016</td>\n",
       "      <td>Personal research</td>\n",
       "      <td>CLOSED</td>\n",
       "      <td>YES</td>\n",
       "      <td>—</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2016-11-25 (07:50:14.305) HKT</td>\n",
       "      <td>DOH</td>\n",
       "      <td>Incidence of diarrhea, constipation, and respi...</td>\n",
       "      <td>11/25/2010 - 11/25/2016</td>\n",
       "      <td>Research</td>\n",
       "      <td>PARTIALLY SUCCESSFUL</td>\n",
       "      <td>YES</td>\n",
       "      <td>—</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>91575</th>\n",
       "      <td>2021-12-31 (22:33:51.182) HKT</td>\n",
       "      <td>DepEd</td>\n",
       "      <td>HAZARD PAY</td>\n",
       "      <td>08/06/2021 - 09/15/2021</td>\n",
       "      <td>For Clarification</td>\n",
       "      <td>SUCCESSFUL</td>\n",
       "      <td>NO</td>\n",
       "      <td>—</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>91576</th>\n",
       "      <td>2021-12-31 (22:39:04.934) HKT</td>\n",
       "      <td>NAP</td>\n",
       "      <td>Election results of Zamboanga City local elect...</td>\n",
       "      <td>01/01/1937 - 12/31/1955</td>\n",
       "      <td>Research project on local history</td>\n",
       "      <td>PENDING</td>\n",
       "      <td>NO</td>\n",
       "      <td>—</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>91577</th>\n",
       "      <td>2021-12-31 (22:46:38.459) HKT</td>\n",
       "      <td>NHCP</td>\n",
       "      <td>Election results of Zamboanga City local elect...</td>\n",
       "      <td>01/01/1955 - 12/31/2004</td>\n",
       "      <td>Research project on local history</td>\n",
       "      <td>REFERRED</td>\n",
       "      <td>NO</td>\n",
       "      <td>—</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>91578</th>\n",
       "      <td>2021-12-31 (23:02:53.564) HKT</td>\n",
       "      <td>DOJ</td>\n",
       "      <td>BRANCH AND DOCKET NO</td>\n",
       "      <td>11/15/2021 - 12/31/2021</td>\n",
       "      <td>SCHEDULE OF HEARING</td>\n",
       "      <td>SUCCESSFUL</td>\n",
       "      <td>NO</td>\n",
       "      <td>—</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>91579</th>\n",
       "      <td>2021-12-31 (23:25:32.671) HKT</td>\n",
       "      <td>PAO</td>\n",
       "      <td>PAO</td>\n",
       "      <td>11/15/2021 - 12/31/2021</td>\n",
       "      <td>Advise and help from our case</td>\n",
       "      <td>SUCCESSFUL</td>\n",
       "      <td>NO</td>\n",
       "      <td>—</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>91580 rows × 8 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                        DATE CREATED AGENCY  \\\n",
       "0      2016-11-25 (01:26:40.574) HKT   DOTr   \n",
       "1      2016-11-25 (01:35:34.481) HKT    PNP   \n",
       "2      2016-11-25 (02:22:02.812) HKT   DICT   \n",
       "3      2016-11-25 (07:33:31.050) HKT    DOH   \n",
       "4      2016-11-25 (07:50:14.305) HKT    DOH   \n",
       "...                              ...    ...   \n",
       "91575  2021-12-31 (22:33:51.182) HKT  DepEd   \n",
       "91576  2021-12-31 (22:39:04.934) HKT    NAP   \n",
       "91577  2021-12-31 (22:46:38.459) HKT   NHCP   \n",
       "91578  2021-12-31 (23:02:53.564) HKT    DOJ   \n",
       "91579  2021-12-31 (23:25:32.671) HKT    PAO   \n",
       "\n",
       "                            TITLE OF REQUESTED DOCUMENTS  \\\n",
       "0                                clark green city update   \n",
       "1           Crime Statatistics and Programs to Combat it   \n",
       "2                            List of .gov.ph sub-domains   \n",
       "3                           HIV stats in the Philippines   \n",
       "4      Incidence of diarrhea, constipation, and respi...   \n",
       "...                                                  ...   \n",
       "91575                                         HAZARD PAY   \n",
       "91576  Election results of Zamboanga City local elect...   \n",
       "91577  Election results of Zamboanga City local elect...   \n",
       "91578                               BRANCH AND DOCKET NO   \n",
       "91579                                                PAO   \n",
       "\n",
       "               PERIOD/COVERAGE                            PURPOSE  \\\n",
       "0      11/25/2016 - 11/25/2016                         for update   \n",
       "1      01/01/2000 - 11/25/2016                       School Paper   \n",
       "2      11/25/2015 - 11/25/2016           Research and development   \n",
       "3      11/25/2015 - 11/25/2016                  Personal research   \n",
       "4      11/25/2010 - 11/25/2016                           Research   \n",
       "...                        ...                                ...   \n",
       "91575  08/06/2021 - 09/15/2021                  For Clarification   \n",
       "91576  01/01/1937 - 12/31/1955  Research project on local history   \n",
       "91577  01/01/1955 - 12/31/2004  Research project on local history   \n",
       "91578  11/15/2021 - 12/31/2021                SCHEDULE OF HEARING   \n",
       "91579  11/15/2021 - 12/31/2021      Advise and help from our case   \n",
       "\n",
       "                     STATUS EXTENDED? REASON FOR DENIAL  \n",
       "0                    CLOSED        NO                 —  \n",
       "1                    CLOSED        NO                 —  \n",
       "2                  ACCEPTED        NO                 —  \n",
       "3                    CLOSED       YES                 —  \n",
       "4      PARTIALLY SUCCESSFUL       YES                 —  \n",
       "...                     ...       ...               ...  \n",
       "91575            SUCCESSFUL        NO                 —  \n",
       "91576               PENDING        NO                 —  \n",
       "91577              REFERRED        NO                 —  \n",
       "91578            SUCCESSFUL        NO                 —  \n",
       "91579            SUCCESSFUL        NO                 —  \n",
       "\n",
       "[91580 rows x 8 columns]"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df2 = pd.read_csv('eFOI Raw Data as of 31 December 2021.xlsx - Raw Data as of 31 December 2021.csv')\n",
    "df2"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a1ac3816",
   "metadata": {},
   "source": [
    "Offhand, you will notice already that two columns are unique here vs. the first df: **extended?** and **reason_denial** which explains reasons for denial. \n",
    "\n",
    "We decided to just **drop** the two for now here. We may get back to **reason_denial** during our analysis.\n",
    "\n",
    "Take note that the **first df** likewise have a unique column for **link**. We will keep that just to ensure we can go back to them for analysis later. That means when this both are merged, there will be **NaNs** under **link**."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4ca7b738",
   "metadata": {},
   "source": [
    "## Cleaning df2\n",
    "\n",
    "### Rename the columns"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "258d3be4",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>date</th>\n",
       "      <th>agency</th>\n",
       "      <th>title</th>\n",
       "      <th>period_covered</th>\n",
       "      <th>purpose</th>\n",
       "      <th>status</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2016-11-25 (01:26:40.574) HKT</td>\n",
       "      <td>DOTr</td>\n",
       "      <td>clark green city update</td>\n",
       "      <td>11/25/2016 - 11/25/2016</td>\n",
       "      <td>for update</td>\n",
       "      <td>CLOSED</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2016-11-25 (01:35:34.481) HKT</td>\n",
       "      <td>PNP</td>\n",
       "      <td>Crime Statatistics and Programs to Combat it</td>\n",
       "      <td>01/01/2000 - 11/25/2016</td>\n",
       "      <td>School Paper</td>\n",
       "      <td>CLOSED</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2016-11-25 (02:22:02.812) HKT</td>\n",
       "      <td>DICT</td>\n",
       "      <td>List of .gov.ph sub-domains</td>\n",
       "      <td>11/25/2015 - 11/25/2016</td>\n",
       "      <td>Research and development</td>\n",
       "      <td>ACCEPTED</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2016-11-25 (07:33:31.050) HKT</td>\n",
       "      <td>DOH</td>\n",
       "      <td>HIV stats in the Philippines</td>\n",
       "      <td>11/25/2015 - 11/25/2016</td>\n",
       "      <td>Personal research</td>\n",
       "      <td>CLOSED</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2016-11-25 (07:50:14.305) HKT</td>\n",
       "      <td>DOH</td>\n",
       "      <td>Incidence of diarrhea, constipation, and respi...</td>\n",
       "      <td>11/25/2010 - 11/25/2016</td>\n",
       "      <td>Research</td>\n",
       "      <td>PARTIALLY SUCCESSFUL</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>91575</th>\n",
       "      <td>2021-12-31 (22:33:51.182) HKT</td>\n",
       "      <td>DepEd</td>\n",
       "      <td>HAZARD PAY</td>\n",
       "      <td>08/06/2021 - 09/15/2021</td>\n",
       "      <td>For Clarification</td>\n",
       "      <td>SUCCESSFUL</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>91576</th>\n",
       "      <td>2021-12-31 (22:39:04.934) HKT</td>\n",
       "      <td>NAP</td>\n",
       "      <td>Election results of Zamboanga City local elect...</td>\n",
       "      <td>01/01/1937 - 12/31/1955</td>\n",
       "      <td>Research project on local history</td>\n",
       "      <td>PENDING</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>91577</th>\n",
       "      <td>2021-12-31 (22:46:38.459) HKT</td>\n",
       "      <td>NHCP</td>\n",
       "      <td>Election results of Zamboanga City local elect...</td>\n",
       "      <td>01/01/1955 - 12/31/2004</td>\n",
       "      <td>Research project on local history</td>\n",
       "      <td>REFERRED</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>91578</th>\n",
       "      <td>2021-12-31 (23:02:53.564) HKT</td>\n",
       "      <td>DOJ</td>\n",
       "      <td>BRANCH AND DOCKET NO</td>\n",
       "      <td>11/15/2021 - 12/31/2021</td>\n",
       "      <td>SCHEDULE OF HEARING</td>\n",
       "      <td>SUCCESSFUL</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>91579</th>\n",
       "      <td>2021-12-31 (23:25:32.671) HKT</td>\n",
       "      <td>PAO</td>\n",
       "      <td>PAO</td>\n",
       "      <td>11/15/2021 - 12/31/2021</td>\n",
       "      <td>Advise and help from our case</td>\n",
       "      <td>SUCCESSFUL</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>91580 rows × 6 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                date agency  \\\n",
       "0      2016-11-25 (01:26:40.574) HKT   DOTr   \n",
       "1      2016-11-25 (01:35:34.481) HKT    PNP   \n",
       "2      2016-11-25 (02:22:02.812) HKT   DICT   \n",
       "3      2016-11-25 (07:33:31.050) HKT    DOH   \n",
       "4      2016-11-25 (07:50:14.305) HKT    DOH   \n",
       "...                              ...    ...   \n",
       "91575  2021-12-31 (22:33:51.182) HKT  DepEd   \n",
       "91576  2021-12-31 (22:39:04.934) HKT    NAP   \n",
       "91577  2021-12-31 (22:46:38.459) HKT   NHCP   \n",
       "91578  2021-12-31 (23:02:53.564) HKT    DOJ   \n",
       "91579  2021-12-31 (23:25:32.671) HKT    PAO   \n",
       "\n",
       "                                                   title  \\\n",
       "0                                clark green city update   \n",
       "1           Crime Statatistics and Programs to Combat it   \n",
       "2                            List of .gov.ph sub-domains   \n",
       "3                           HIV stats in the Philippines   \n",
       "4      Incidence of diarrhea, constipation, and respi...   \n",
       "...                                                  ...   \n",
       "91575                                         HAZARD PAY   \n",
       "91576  Election results of Zamboanga City local elect...   \n",
       "91577  Election results of Zamboanga City local elect...   \n",
       "91578                               BRANCH AND DOCKET NO   \n",
       "91579                                                PAO   \n",
       "\n",
       "                period_covered                            purpose  \\\n",
       "0      11/25/2016 - 11/25/2016                         for update   \n",
       "1      01/01/2000 - 11/25/2016                       School Paper   \n",
       "2      11/25/2015 - 11/25/2016           Research and development   \n",
       "3      11/25/2015 - 11/25/2016                  Personal research   \n",
       "4      11/25/2010 - 11/25/2016                           Research   \n",
       "...                        ...                                ...   \n",
       "91575  08/06/2021 - 09/15/2021                  For Clarification   \n",
       "91576  01/01/1937 - 12/31/1955  Research project on local history   \n",
       "91577  01/01/1955 - 12/31/2004  Research project on local history   \n",
       "91578  11/15/2021 - 12/31/2021                SCHEDULE OF HEARING   \n",
       "91579  11/15/2021 - 12/31/2021      Advise and help from our case   \n",
       "\n",
       "                     status  \n",
       "0                    CLOSED  \n",
       "1                    CLOSED  \n",
       "2                  ACCEPTED  \n",
       "3                    CLOSED  \n",
       "4      PARTIALLY SUCCESSFUL  \n",
       "...                     ...  \n",
       "91575            SUCCESSFUL  \n",
       "91576               PENDING  \n",
       "91577              REFERRED  \n",
       "91578            SUCCESSFUL  \n",
       "91579            SUCCESSFUL  \n",
       "\n",
       "[91580 rows x 6 columns]"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df2.columns = ['date', 'agency', 'title', 'period_covered', 'purpose', 'status', 'extended', 'reason_denial']\n",
    "df2 = df2.drop(['reason_denial', 'extended'], axis= 1)\n",
    "df2"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "131cb24a",
   "metadata": {},
   "source": [
    "### Convert date to date time\n",
    "\n",
    "We use regex here."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "a8359185",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>date</th>\n",
       "      <th>agency</th>\n",
       "      <th>title</th>\n",
       "      <th>period_covered</th>\n",
       "      <th>purpose</th>\n",
       "      <th>status</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2016-11-25</td>\n",
       "      <td>DOTr</td>\n",
       "      <td>clark green city update</td>\n",
       "      <td>11/25/2016 - 11/25/2016</td>\n",
       "      <td>for update</td>\n",
       "      <td>CLOSED</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2016-11-25</td>\n",
       "      <td>PNP</td>\n",
       "      <td>Crime Statatistics and Programs to Combat it</td>\n",
       "      <td>01/01/2000 - 11/25/2016</td>\n",
       "      <td>School Paper</td>\n",
       "      <td>CLOSED</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2016-11-25</td>\n",
       "      <td>DICT</td>\n",
       "      <td>List of .gov.ph sub-domains</td>\n",
       "      <td>11/25/2015 - 11/25/2016</td>\n",
       "      <td>Research and development</td>\n",
       "      <td>ACCEPTED</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2016-11-25</td>\n",
       "      <td>DOH</td>\n",
       "      <td>HIV stats in the Philippines</td>\n",
       "      <td>11/25/2015 - 11/25/2016</td>\n",
       "      <td>Personal research</td>\n",
       "      <td>CLOSED</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2016-11-25</td>\n",
       "      <td>DOH</td>\n",
       "      <td>Incidence of diarrhea, constipation, and respi...</td>\n",
       "      <td>11/25/2010 - 11/25/2016</td>\n",
       "      <td>Research</td>\n",
       "      <td>PARTIALLY SUCCESSFUL</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "        date agency                                              title  \\\n",
       "0 2016-11-25   DOTr                            clark green city update   \n",
       "1 2016-11-25    PNP       Crime Statatistics and Programs to Combat it   \n",
       "2 2016-11-25   DICT                        List of .gov.ph sub-domains   \n",
       "3 2016-11-25    DOH                       HIV stats in the Philippines   \n",
       "4 2016-11-25    DOH  Incidence of diarrhea, constipation, and respi...   \n",
       "\n",
       "            period_covered                   purpose                status  \n",
       "0  11/25/2016 - 11/25/2016                for update                CLOSED  \n",
       "1  01/01/2000 - 11/25/2016              School Paper                CLOSED  \n",
       "2  11/25/2015 - 11/25/2016  Research and development              ACCEPTED  \n",
       "3  11/25/2015 - 11/25/2016         Personal research                CLOSED  \n",
       "4  11/25/2010 - 11/25/2016                  Research  PARTIALLY SUCCESSFUL  "
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df2['date'] = df2.date.str.replace(\"HKT\", \"\")\n",
    "df2['date'] = df2.date.str.replace(r'[()](\\d\\d[:]\\d\\d[:]\\d\\d[.]\\d\\d\\d)[()]', '', regex=True)\n",
    "df2.date = pd.to_datetime(df2.date)\n",
    "df2.head()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c0ed299d",
   "metadata": {},
   "source": [
    "## Merging the dfs\n",
    "\n",
    "Combine the two dfs into one"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "19226315",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>agency</th>\n",
       "      <th>date</th>\n",
       "      <th>title</th>\n",
       "      <th>status</th>\n",
       "      <th>purpose</th>\n",
       "      <th>period_covered</th>\n",
       "      <th>link</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>DOTr</td>\n",
       "      <td>2016-11-25</td>\n",
       "      <td>SALN of Bongbong Marcos</td>\n",
       "      <td>DENIED</td>\n",
       "      <td>School Paper Research(Thesis)</td>\n",
       "      <td>11/25/2016 - 11/25/2016</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>DICT</td>\n",
       "      <td>2016-11-25</td>\n",
       "      <td>Request for Architecture of SSS, Pagibig, Phil...</td>\n",
       "      <td>ACCEPTED</td>\n",
       "      <td>To validate if our data is properly secured.</td>\n",
       "      <td>01/01/2016 - 11/25/2016</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>PCGG</td>\n",
       "      <td>2016-11-25</td>\n",
       "      <td>HIRING GOVERNMENT CAREER EMPLOYEES (RANK AND F...</td>\n",
       "      <td>DENIED</td>\n",
       "      <td>PUBLIC INFORMATION</td>\n",
       "      <td>11/25/2016 - 11/25/2016</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>PSA</td>\n",
       "      <td>2016-11-25</td>\n",
       "      <td>The amount of yellowfin, skipjack, bigeye tuna...</td>\n",
       "      <td>DENIED</td>\n",
       "      <td>Research and Development</td>\n",
       "      <td>01/01/2010 - 12/31/2015</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>PCOO</td>\n",
       "      <td>2016-11-25</td>\n",
       "      <td>HIRING GOVERNMENT CAREER EMPLOYEES (RANK AND F...</td>\n",
       "      <td>PARTIALLY SUCCESSFUL</td>\n",
       "      <td>PUBLIC INFORMATION</td>\n",
       "      <td>11/25/2016 - 11/25/2016</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>96087</th>\n",
       "      <td>DOH</td>\n",
       "      <td>2022-01-20</td>\n",
       "      <td>Floor plan of Tondo Medical Center</td>\n",
       "      <td>PENDING</td>\n",
       "      <td>Academic Case Study</td>\n",
       "      <td>01/20/2022 - 01/20/2022</td>\n",
       "      <td>https://www.foi.gov.ph/requests/aglzfmVmb2ktcG...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>96088</th>\n",
       "      <td>BOI</td>\n",
       "      <td>2022-01-20</td>\n",
       "      <td>Herbal/Medicinal Plant Industry</td>\n",
       "      <td>PENDING</td>\n",
       "      <td>Thesis Research</td>\n",
       "      <td>01/01/2017 - 11/27/2021</td>\n",
       "      <td>https://www.foi.gov.ph/requests/aglzfmVmb2ktcG...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>96089</th>\n",
       "      <td>DTI</td>\n",
       "      <td>2022-01-20</td>\n",
       "      <td>Companies in the Herbal or Medicinal Plant Ind...</td>\n",
       "      <td>PENDING</td>\n",
       "      <td>Thesis Research</td>\n",
       "      <td>01/01/2017 - 11/27/2021</td>\n",
       "      <td>https://www.foi.gov.ph/requests/aglzfmVmb2ktcG...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>96090</th>\n",
       "      <td>ECC</td>\n",
       "      <td>2022-01-20</td>\n",
       "      <td>COvid positive sickness Benifits</td>\n",
       "      <td>PENDING</td>\n",
       "      <td>Question or Inquiry</td>\n",
       "      <td>12/31/2021 - 01/16/2022</td>\n",
       "      <td>https://www.foi.gov.ph/requests/aglzfmVmb2ktcG...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>96091</th>\n",
       "      <td>PSA</td>\n",
       "      <td>2022-01-20</td>\n",
       "      <td>Copy of PSA Birth certificate (Mary Anne Robis...</td>\n",
       "      <td>PENDING</td>\n",
       "      <td>Clarification for Misrepresentation of COC</td>\n",
       "      <td>01/20/1950 - 01/20/2022</td>\n",
       "      <td>https://www.foi.gov.ph/requests/aglzfmVmb2ktcG...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>96092 rows × 7 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "      agency       date                                              title  \\\n",
       "0       DOTr 2016-11-25                            SALN of Bongbong Marcos   \n",
       "1       DICT 2016-11-25  Request for Architecture of SSS, Pagibig, Phil...   \n",
       "2       PCGG 2016-11-25  HIRING GOVERNMENT CAREER EMPLOYEES (RANK AND F...   \n",
       "3        PSA 2016-11-25  The amount of yellowfin, skipjack, bigeye tuna...   \n",
       "4       PCOO 2016-11-25  HIRING GOVERNMENT CAREER EMPLOYEES (RANK AND F...   \n",
       "...      ...        ...                                                ...   \n",
       "96087    DOH 2022-01-20                 Floor plan of Tondo Medical Center   \n",
       "96088    BOI 2022-01-20                    Herbal/Medicinal Plant Industry   \n",
       "96089    DTI 2022-01-20  Companies in the Herbal or Medicinal Plant Ind...   \n",
       "96090    ECC 2022-01-20                   COvid positive sickness Benifits   \n",
       "96091    PSA 2022-01-20  Copy of PSA Birth certificate (Mary Anne Robis...   \n",
       "\n",
       "                     status                                       purpose  \\\n",
       "0                    DENIED                 School Paper Research(Thesis)   \n",
       "1                  ACCEPTED  To validate if our data is properly secured.   \n",
       "2                    DENIED                            PUBLIC INFORMATION   \n",
       "3                    DENIED                      Research and Development   \n",
       "4      PARTIALLY SUCCESSFUL                            PUBLIC INFORMATION   \n",
       "...                     ...                                           ...   \n",
       "96087               PENDING                           Academic Case Study   \n",
       "96088               PENDING                               Thesis Research   \n",
       "96089               PENDING                               Thesis Research   \n",
       "96090               PENDING                           Question or Inquiry   \n",
       "96091               PENDING    Clarification for Misrepresentation of COC   \n",
       "\n",
       "                period_covered  \\\n",
       "0      11/25/2016 - 11/25/2016   \n",
       "1      01/01/2016 - 11/25/2016   \n",
       "2      11/25/2016 - 11/25/2016   \n",
       "3      01/01/2010 - 12/31/2015   \n",
       "4      11/25/2016 - 11/25/2016   \n",
       "...                        ...   \n",
       "96087  01/20/2022 - 01/20/2022   \n",
       "96088  01/01/2017 - 11/27/2021   \n",
       "96089  01/01/2017 - 11/27/2021   \n",
       "96090  12/31/2021 - 01/16/2022   \n",
       "96091  01/20/1950 - 01/20/2022   \n",
       "\n",
       "                                                    link  \n",
       "0                                                    NaN  \n",
       "1                                                    NaN  \n",
       "2                                                    NaN  \n",
       "3                                                    NaN  \n",
       "4                                                    NaN  \n",
       "...                                                  ...  \n",
       "96087  https://www.foi.gov.ph/requests/aglzfmVmb2ktcG...  \n",
       "96088  https://www.foi.gov.ph/requests/aglzfmVmb2ktcG...  \n",
       "96089  https://www.foi.gov.ph/requests/aglzfmVmb2ktcG...  \n",
       "96090  https://www.foi.gov.ph/requests/aglzfmVmb2ktcG...  \n",
       "96091  https://www.foi.gov.ph/requests/aglzfmVmb2ktcG...  \n",
       "\n",
       "[96092 rows x 7 columns]"
      ]
     },
     "execution_count": 22,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_final = pd.concat([df,df2]).drop_duplicates().reset_index(drop=True)\n",
    "df_final = df_final.sort_values('date').reset_index(drop=True)\n",
    "df_final"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5607d220",
   "metadata": {},
   "source": [
    "## Save combined df to CSV"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "c23996a2",
   "metadata": {},
   "outputs": [],
   "source": [
    "#df_final.to_csv(\"foi.csv\", index=False)\n",
    "#pd.read_csv(\"foi.csv\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
